### PR TITLE
21 smallrye langchain abstraction

### PR DESCRIPTION
**Pull request by yblazart**

### CODE REVIEW

**Comment by TheEliteGentleman** [comment]
Fixed the merge conflicts.

**Comment by TheEliteGentleman** [comment]
Merged and squashed this branch.

**Review by Emily-Jiang — CHANGES_REQUESTED** [review]
We need to discuss this on 28th Oct regarding the forking of LangChain4J APIs. I suggest to adopt that APIs instead of forking them as we will have to sync up with the upstream down the road.

**Comment by TheEliteGentleman** [comment]
Closing as many of my changes have already been merged in various PRs.

**Comment by ehsavoie** [comment]
Superseded by https://github.com/smallrye/smallrye-llm/pull/53

**Pull request closed without merging**
